name: Personal Capital w/ Budgeting
description: 💵 Personal Capital component for Home Assistant that pulls in budgeting data
type: component
keywords:
  - sensor
  - personalcapital
  - finance
  - money
  - accounts
author:
  name: Chuck Hotaling
  email: hoopie165@gmail.com
  homepage: https://github.com/chotaling1/sensor.personalcapital
license: MIT
files:
  - custom_components/personalcapital/sensor.py
  - custom_components/personalcapital/personalcapitallocal.py
